### ISSUE TITLE
Forward Slash in Headings breaks pagebreak

### ISSUE THREAD

**Issue by 2regenth** [elb-min-uhh/atom-elearnjs#1]
Ok so this is my understanding right now (havent looked at the code)
When exporting to HTML for each heading a placeholder will be added in the form of:
```
|||Headingname///
```
Which is then replaced (through some sort of regex?!) with:
```
</section>
<section markdown="X" name="Headingname" >
```

Hoewever if the heading contains a `/` e.g.: `A / Heading` this fails resulting in:
```
<p>|||A / Heading///</p>
```
being added to the HTML file

**Comment by westarne** [comment]
I guess I will change this exact syntax and fix this problem with escaping.
Working on it.

**Comment by westarne** [comment]
The fix will be applied with the next update comming today or tomorrow most likely.

**Comment by westarne** [comment]
There were syntax changes. Closing slahes `///` will become `|||`. Please check on https://github.com/elb-min-uhh/atom-elearnjs/ README for more information.
