### ISSUE TITLE
"Export linked files into asset folder" corrupts files which are already in the asset folder

### ISSUE THREAD

**Issue by 2regenth** [elb-min-uhh/atom-elearnjs#2]
When all assets are already in their respective location inside the assets folder, they will be overwritten with a 0 Byte file.

**Comment by westarne** [comment]
Doesn't happen for me using windows for testing. Have you tried it multiple times? It seems to sometimes file on files, when the filesystem has them locked.

**Comment by westarne** [comment]
Where only the linked files like images corrupted or all the assets? And are you sure you were using the latest published Version (v0.2.2)?

**Comment by 2regenth** [comment]
Yes, it happens every time.
All elearn.js assets are still working, only manually copied assets were overwritten (only images, as i dont have any other custom assets at the moment)

If i move the images out of the asset folder they are copied successfully.
Also youre writing "linked" so im assuming it should create some sort of symlink? instead of just copying it

Right now if i had to guess there is some sort of copy command like:
```
cp img.png img.png
```
which results in the file being "created" (replaced with a 0 byte file) and then copied, at which point it already reads back the new 0 Byte copy

Im running Atom 1.25.1x64 with atom-elearn.js 0.2.2 on Arch Linux.
Is there a Log window of some sort i could take a look at?

**Comment by westarne** [comment]
Ok, Either way the problem is as you assumed the copy process. A basic node read-write stream (used for copying) leads to this empty file. Patch will be online in a few minutes.

**Comment by westarne** [comment]
Btw. the word "linked" refers to the "link" in the markdown source code. Meaning that every file (within certain elements) will be copied

**Comment by westarne** [comment]
Should be fixed (in v0.2.4). If not please create a new issue referring to this.
