### ISSUE TITLE
[Suggestion] Option to exclude comments in final HTML file

### ISSUE THREAD

**Issue by 2regenth** [elb-min-uhh/atom-elearnjs#4]
When writing a markdown file one might want to include comments only meant for the author of the file or comment out sections which are no longer needed but should still be kept in the document as a reference point later on. 
An option to exclude these sections from the final HTML file would be great.

for example let's say i have this as a comment in my markdown file:
`<!-- Some secret notes which should not be in the publicly available html file -->` it would  be copied into the html file which in this case is not desireable.

I would suggest either an option to exclude all not as special (hide in overview and such) recognized comments or to introduce a new prefix which would skip certain comments from being included:
`<!--hide This is a secret hidden comment-->`

**Comment by westarne** [comment]
This is a good suggestion. I will look into ways to implement this.

Most likely it will be some general option (in the atom settings) and the additional `<!--hide ... -->` syntax.
