### ISSUE TITLE
Unable to convert .md to .html or .pdf

### ISSUE THREAD

**Issue by nielsgeo** [elb-min-uhh/atom-elearnjs#5]
When trying to convert .md to either .html or .pdf I receive an error:

> Could not save the file
> TypeError: Cannot read property 'C:\Users\user\Desktop\test.md' of undefined

I tried with different .md files saved at various locations and got same error. Most likely the .md file itself does not cause the error.

**Comment by westarne** [comment]
This does indeed sound like some error in the plugin. Which versions of atom-elearnjs and atom do you currently use?
Is there more information in the error message like code lines or files named which led to the error, typically looking like this "SomeFileName.js (127:12)" or similar?

I'll try to repoduce the error and work on a fix.

**Comment by westarne** [comment]
I have an idea on where the problem is. Does the error message appear before even getting the "Export Option" Popup?

**Comment by nielsgeo** [comment]
the message appears after the export options and even after the "converting" message pops up (see screenshot)
Atom 1.33.0 ia32
atom-elearnjs 0.6.4

![error_atom](https://user-images.githubusercontent.com/22545097/50162731-52b3fa00-02df-11e9-921e-59be26d73778.PNG)

In addition I found that ctrl+alt+o / p and the respective entries in the context menu do not work. When I click these or press the keys nothing happens. Only "elearn.js - save as..." triggers the export options popup and attempt to export.

**Comment by westarne** [comment]
I could not explicitly reproduce the latter but I published version 0.6.5 which should fix the first problem, hopefully. Though it might forget all your stored "save locations" of files you exported previously.

Please check the new Version and tell me if it is fixed for you.

**Comment by nielsgeo** [comment]
Export to html works fine, including hotkey and context menu entries. 
Export to pdf seems to be OK as well, however conversion needs very long time. I stopped the conversion before the file was created. I think with a changed delay setting I will manage to export to pdf.
Thanks a lot for the quick support!

**Comment by westarne** [comment]
Ok, I'm glad that the fix worked.
The conversion time will (most likely) not get faster in the future. The time is mostly the chromium startup. Thus the first pdf export (after starting atom) will always be slow. Consecutive exports after that will most likely be faster as the OS optimizes the startup time, especially if the "Keep Chrome Running" setting is activated. Chrome will then be started on the first export and kept alive until Atom is closed. This will increase the memory usage usually for about 35-50 MB. You can check this on a Windows computer in the Task-Manager when expanding the Atom entry.
With "Kepp Chrome Running" and already started and a render delay of 0, my computer usually needs 1s to export to PDF. Depending on the computer the startup of Chrome might take 5 or even more seconds.
