### ISSUE TITLE
saving as HTML, or PDF not working

### ISSUE THREAD

**Issue by codeHorse87** [elb-min-uhh/atom-elearnjs#6]
**Describe the bug**
saving as HTML, or PDF not working via atom plugin on Mac OS

**To Reproduce**
1. Go to elearn.js compatible markdown file 
2. Click on Packages -> elearn.js -> "Save As HTML"
3. confirm default path for saving
4. nothing happens, no error message but as well no file is written, or overwritten

**Expected behavior**
HTML or PDF export file should be written on the selected path

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Editor Atom 1.57.0
 - Plugin Version 0.6.5

**Additional context**
I debugged the behavior to Util.js line 33

`
        let filePath = await new Promise((res) => {
            dialog.showSaveDialog({
                defaultPath: defaultPath,
                filters: filters,
            }, res);
        });

        return filePath;
`
The promise does not return a filePath, after the dialog is displayed and the path confirmed. The same behavior does not occur with VSCode and the vscode elearn.js plugin on the same system. I don't know about Electron but it seems it has something to do with how the save dialog is called.

**Comment by mheinecke** [comment]
Hello codeHorse87,

thanks for the bug report. I could verify the behaviour on MacOS Big Sur. On the long run we want to get rid of the Electron based workflow because of too many dependencies. The future will be an editor HTML-Page with export funktion. Currently we are reworking the UI and constructing he general architecture.

But for the intermediate period we like to implement your bugfix.
Michael

**Comment by codeHorse87** [comment]
Hi @mheinecke 
Thanks for the quick reply. Does it have something to do with [LiaScript](https://liascript.github.io/) which is already using elearn.js? 
To ease up the setup for our authors we're thinking about hosting a CodiMD with elearn.js embedded. 
Let me know about the progress. We might be able to support the development, testing, or documentation.

**Comment by codeHorse87** [comment]
@mheinecke I've created a pull request with a fix to the issue. I appreciate if ¥ou can apply the fix

**Comment by codeHorse87** [comment]
Hi @SpaceCafe can I kindly ask you to run an `apm publish` for the atom package repository? 
Thanks in advance!
